### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [polotno-project/polotno-studio#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by ayshptk** [comment]
Still I see no LICENSE file

**Comment by dunossauro** [comment]
Any plans to create a license file?

The @TechnologyClassroom GLP suggestion is really amazing

**Comment by lavrton** [comment]
I added MIT

**Comment by TechnologyClassroom** [comment]
Are there any plans to free the [Polotno SDK license](https://polotno.com/license)?

**Comment by lavrton** [comment]
Short answer no.

But I am thinking to open some parts of it. I am not certain how to organize `npm` packages and API yet. I want to open some UI components.

**Comment by TechnologyClassroom** [comment]
I do appreciate being up front about it. I have seen a few projects try to appear to be free while hiding the fact that they have non-free required dependencies.

**Comment by tejashcrest** [comment]
Does it really serve MIT License terms?
