### ISSUE TITLE
How can i fix the search bar icon in side panel tabs ?

### ISSUE THREAD

**Issue by SohaibAshraf1** [polotno-project/polotno-studio#20]
![icon](https://user-images.githubusercontent.com/115225219/197470069-73e2bc82-f885-4df4-8127-fbb8448c7879.PNG)

After I modified the template default name as sample templates, the icon in the search bar was moved from its original location. Is there a way to make it better?

**Comment by lavrton** [comment]
Interesting. Is a way to reproduce it in the codesandbox?Do you have any custom styles?

**Comment by SohaibAshraf1** [comment]
I just fixed it by applying custom styles in index.css
