### ISSUE TITLE
CORS issues for S3 images

### ISSUE THREAD

**Issue by scriptscrypt** [polotno-project/polotno-studio#29]
The Image is being loaded from S3 bucket [allowed for all domains], it's being shown on the custom sidepanel but not on the Canvas.
canvas error : "Can't load image"

**Comment by lavrton** [comment]
I added docs here: https://polotno.com/docs/cors. I hope it will help. The second step may fix your issue (you may need to clear cache and hard reload).
Let me know if you still have any questions.
