### ISSUE TITLE
Can new pages be added with some pre-filled attributes?

### ISSUE THREAD

**Issue by ADTC** [polotno-project/polotno-studio#41]
Currently all new pages added by clicking the `+` sign in the timeline / page thumbnails or by clicking the `+` button in the canvas (above each page), they are always with default attributes.

I was hoping to pre-fill any newly created pages with a custom set of attributes (the same argument typically passed to `page.set(attr)`). Would this be possible by any chance?

**Comment by lavrton** [comment]
The programmatic solution can be this:

```js
let lastPagesIds = [];
store.on('change', () => {
  const newPages = store.pages.filter(page => !lastPagesIds.includes(page.id));
  
  newPages.forEach(page => {
    page.set({});
  })

  // Update the lastPagesIds to reflect the current state
  lastPagesIds = store.pages.map(page => page.id);
});
```

**Comment by ADTC** [comment]
Almost, except it runs on duplicated pages as well. Since I'm trying to set a custom attribute, I figured I can just check for the attribute.

```ts
  newPages.forEach((page) => {
    // Duplicated pages will already have the custom attribute
    if (page.custom?.myAttribute) return

    page.set({
      duration,
      custom: {
        myAttribute: 'My attribute value',
      },
    })
  })
```

Thank you for you help! Though It would have been nice if we could just set the default attributes in `createStore`.

**Comment by lavrton** [comment]
Good suggestion. Added to the backlog: https://github.com/polotno-project/polotno-board/issues/81
