### ISSUE TITLE
[Animations Beta] The page thumbnail block in timeline becomes too thin if the duration is too small

### ISSUE THREAD

**Issue by ADTC** [polotno-project/polotno-studio#42]
Imagine several pages with 0.1s duration each. They become so thin on the timeline that it's hard to click the correct page in the timeline. Is it possible to set a minimum width for the page thumbnails?

I tried adding a CSS like this:

```css
/* The page block in timeline shouldn't become too thin. */
.go757440592 {
  min-width: 60px;
}
```

But the issues:

1. There's no guarantee that `go757440592` will not change to some other generated class name in future. (Polotno has a problem of using a lot of generated class names or reused class names that it's difficult to target specific elements.)

2. During playback, the blue bar that moves along the timeline to indicate current position will get out of sync with the active page just after the playback is completed for a page that has a tiny duration but is `60px` in width.

<img width="296" alt="image" src="https://github.com/user-attachments/assets/30667e11-2c0e-46ea-8641-c3abacd28491">

**Comment by ADTC** [comment]
> What is the use case of such short page?

Our page durations are not directly user-editable. They are automatically determined as a factor of the length of text in a custom page attribute. If the text is short or empty, that can lead to such short pages.

> I plan to add "permanent" polotno class names that will be safe to use.

Thank you. In order to make the  page durations not directly user-editable, we:
* remove the drag handle used to change page duration in the timeline.
* disable the button in toolbar which shows a slider to change the duration.

Targeting these two things (and others for various reasons) is what made me raise the complaint about the lack of unique class names.

**Comment by ADTC** [comment]
Hi @lavrton I updated the previous comment with code snippets to show the difficulty. Please check.

**Comment by lavrton** [comment]
Added some classes in a new version. You can inspect.

But in general, if you need a lot of customization, it may be better to remove the default component and just implement your own version with full control.

**Comment by ADTC** [comment]
Thanks @lavrton I updated to `v2.13.10` but I didn't find any new classes for the above cases upon inspection. Would you mind listing the added classes here? Thank you.

**Comment by ADTC** [comment]
Regarding this btw, I noticed that in Canva the page thumbnail is at least a square, if not longer (making a horizontal rectangle), but it will never become a vertical rectangle. Instead, when the animations are playing, the temporal position indicator bar moves faster in the page thumbnails with a short duration.


https://github.com/user-attachments/assets/1541b7df-c61c-4321-a8fe-a3200688bec4



Hopefully you can implement something similar. I think in order to achieve this, the bar should be part of the page thumbnail, not a separate element that is moved over the timeline. This will also allow gaps to be inserted between the page thumbnails.

**Comment by lavrton** [comment]
For now closing as lower priority.
