### ISSUE TITLE
Upload a PDF file, which can then be put into an Image element which has page of PDF rendered into it

### ISSUE THREAD

**Issue by ADTC** [polotno-project/polotno-studio#45]
What would be the best way to upload a PDF in the Upload panel, then put a PDF page into the Polotno page as an element? It would be similar to an `Image` element, but instead of a static image, it would display a chosen page from the PDF (page 1 by default, but a control could allow choosing a different page). (The page could be rendered as an image.)

Currently there's no support for uploading PDF files. I'm thinking of how our custom Polotno project can be extended somehow to support doing this. Is it possible by extending Image element with custom attributes and having a different way of rendering the `Image` element when those custom attributes are present? (The custom attributes will indicate that the `Image` element should be a PDF, include a PDF file URL/data URI, and maybe a page number.)

Instead of the standard way of rendering static image, it would render a page from the PDF which is something I think we could do [using react-pdf](https://github.com/wojtekmaj/react-pdf?tab=readme-ov-file#usage) if I know how override the Image element's behavior based on custom attributes. Unless the only way to do this is to create my own [custom element](https://polotno.com/docs/custom-element) (the experimental feature).

If we have to create a custom element to achieve this, I would love to take a look at how the `Image` element is implemented (that is, read its source code, and generally the source code of SDK). Is that publicly available? Or could it be obtained with a private Polotno license?

**Comment by lavrton** [comment]
For now, there are no better ways. PDF is not supported directly. Your current solution looks very good to me. I would do exactly the same in such a use case.
