### ISSUE TITLE
upload-section deleted image gets added to the canvas.

### ISSUE THREAD

**Issue by MichaelDimmitt** [polotno-project/polotno-studio#46]
## Issue: 
upload-section adds an image to the canvas when deleting.

## Expected:
Image should be deleted and no image added to the canvas.

## Note: 
If people agree this is an issue.
I submitted a pr to resolve this issue #47. I had to solve this in my own project so I thought id submit the solution for others to benefit. Happy to have further discussion if you have any questions / concerns.

## Why:
ImagesGrid, registers the function `getCredit` first and does the delete action. Next, `ImagesGrid - onSelect` is activated which adds an element to the canvas via addElement.

There is nothing in the callback parameters for either function `getCredit` nor `onSelect` that can identify that a delete has occurred instead of a select. `getCredit`'s buttonClick property: `event.nativeEvent.preventDefault`has no effect on `onSelect`.

## Steps to reproduce:
src/sections/upload-section.js

Uncommenting the following line in App.js:
DEFAULT_SECTIONS.unshift(UploadSection);

add import {UploadSection} from './sections/upload-section' to the top of App.js

## Video of issue: (deleted image is added to the canvas)
https://github.com/user-attachments/assets/18c56f07-819f-4d3f-96bf-9b6109ceb4de

## Video with solution: (deleted image does not get added to the canvas)
https://github.com/user-attachments/assets/8722409a-98d0-4b32-aa6c-85765e048a06

Cheers, 
Michael Dimmitt

**Comment by lavrton** [comment]
Resolved in PR
