### ISSUE TITLE
Feature Request - Better file naming, maybe based on text?

### ISSUE THREAD

**Issue by src-r-r** [polotno-project/polotno-studio#7]
Perhaps this could be an option to select before saving, but like many people I have a lot of `Polotno (#).png` files in my downloads folder that I have to rename. Would it be prudent to automagically create filenames on download?

For instance, if the text is "ACT NOW BEFORE THEY'RE GONE! $40 FOR 3 TICKETS!" then the file can be saved as `act-now-before-theyre-gone-40-for-3-tickets.json` and `act-now-before-theyre-gone-40-for-3-tickets.png`.

**Comment by lavrton** [comment]
It is a good request.

Probably we also can add "project name" input somewhere? Like in the header, similar to other apps.

**Comment by src-r-r** [comment]
How about a vote? React with the emoji for...
👀 = user-defined project name input
🚀 = automatic naming based on text
🎉 = both

**Comment by lavrton** [comment]
Just implemented "automatic naming based on text". I hope it will work better.

**Comment by src-r-r** [comment]
So then it's already closed? I was kind of hoping on taking this, but if you already got a fix, awesome!

**Comment by lavrton** [comment]
Ah. I am sorry. I didn't understand that YOU want to take this.
