### ISSUE TITLE
Corner radius not working correctly with filters

### ISSUE THREAD

**Issue by danielnydrle** [polotno-project/polotno-studio#8]
When I apply one or more effects on an image, followed by the Corner radius effect, the radius is not automatically applied to the image. For the image to actually have the radius applied, it takes toggling the first effect applied off and on again.

Example order of functions to replicate the issue:
1. Grayscale
2. Corner radius
3. Border

This produces a grayscale image with sharp edges and rounded border inside the image itself:
![image](https://user-images.githubusercontent.com/57211233/154099549-8823c9f3-f50b-49cf-83c5-b0b1a4b17eae.png)

When done in reverse order (Border, Corner radius, Grayscale), it works just fine, so it's an effect order related issue.

**Comment by lavrton** [comment]
Should be fixed now. Thanks for the report. Please confirm if it works correctly now.

**Comment by danielnydrle** [comment]
Working well! 👍
